### ISSUE TITLE
Read NectarCAM data on the fly via XRootD

### ISSUE THREAD

**Issue by jlenain** [cta-observatory/nectarchain#3]
It would be nice to have a mechanism to read data on the fly, without having the need to locally import them. One solution may be to read data from the Storage Elements on the EGI grid using the xrootd protocol.

I don't know the details enough, but this might imply to implement new features in [ctapipe_io_nectarcam](https://github.com/cta-observatory/ctapipe_io_nectarcam).

[XRootD](https://github.com/xrootd/xrootd) proposes python bindings (see https://github.com/xrootd/xrootd/tree/master/bindings/python).

@kosack suggested to make a try just using `root://` in the `input_url` of `ctapipe.io.EventSource`. A simple try fails however:

```
>>> from ctapipe.io import event_source, EventSeeker
>>> import XRootD
>>> reader = event_source('root://<SOME_SERVER>/<SOME_PATH>/NectarCAM.Run1388.0001.fits.fz')
Traceback (most recent call last):
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsourcefactory.py", line 59, in _get_product_name
    return super()._get_product_name()
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/core/factory.py", line 158, in _get_product_name
    .format(self.__class__.__name__))
AttributeError: The user has not specified a product for EventSourceFactory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsourcefactory.py", line 102, in event_source
    **kwargs)
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/core/factory.py", line 254, in produce
    instance = factory._instance
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/core/factory.py", line 194, in _instance
    product = self._product
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/core/factory.py", line 171, in _product
    product_name = self._get_product_name()
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsourcefactory.py", line 65, in _get_product_name
    if subclass.is_compatible(self.input_url):
  File "/opt/conda/envs/cta/lib/python3.7/site-packages/ctapipe/io/simteleventsource.py", line 78, in is_compatible
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'root://<SOME_SERVER>/<SOME_PATH>/NectarCAM.Run1388.0001.fits.fz'
```

@kosack also mentioned that `ctapipe` is regularly run on `DIRAC` and so the file accesses are directly performed using the `DIRAC` API. @bregeon , @arrabito , would you have an example on how to do it ? To my understanding, `DIRAC` is using python 2.7, while `ctapipe` is mainly supporting python>=3.5, so I wonder how it is done.

**Comment by kosack** [comment]
As far as I understand it, the files are just requested in the DIRAC job, and it copies them to the scratch disk before the job is run. Inside the job, it's running in a python 3 environment and just works with the local files - it doesn't access any dirac-specific functionality, only at the job definition level.    So if you want to access via xrootd, you'd have to add that functionality to ctapipe I guess, not to DIRAC, unless there is a way for DIRAC to create a link or something to an xrootd file? Might check with @arrabito.

**Comment by arrabito** [comment]
You can configure DIRAC to access input data in different ways. The default policy is by 'Download', that means that files are downloaded by DIRAC on the local scratch disk before the application (i.e. ctapipe) start running. Then the application access them as local files. This is the policy we are currently using in CTA-DIRAC.
Another option is to configure DIRAC to access input data by 'Protocol'. In this case, you have to specify for each site which protocol you want to use (depending on which protocol is supported by the site). Then input data on a given SE are accessed remotely by the job using that protocol without any copy on the scratch disk. This means that the application should be able to use that protocol, for instance using the appropriate python bindings. @jlenain the example you have written is correct, i.e. you should use a protocol url in your application, but one has to check the details. 
The way how DIRAC does the link when using the 'Protocol' policy, at least in the past (I have to check if anything has changed), is that it builds a local catalog (under the form of an xml file) translating the LFNs into local urls for the specified protocol. Then ctapipe should just parse this local catalog to read the input data urls.
From my experience with LHCb jobs, the 'Download' policy is more efficient for long jobs, since you loose some time in downloading input files, but then the I/O on the local files are more efficient than using 'remote' access. However, for short jobs and with large input data, it is more efficient the 'Protocol' policy. 
Finally, one can configure DIRAC either to run jobs only on the sites where input data are located (and in this case you can use both policies), either to run jobs that access files located at distant sites. In the second case, I don't think you can use (or anyway that it is efficient) the 'Protocol' policy.   
If you want I can give it a try preparing a DIRAC job using the 'Protocol' policy and then I will let you know what is needed on ctapipe side (XrootD binding, etc.).

**Comment by kosack** [comment]
Also note that it seems xrootd protocol  for storage element access is marked as "deprecated" in the Dirac manual:

https://dirac.readthedocs.io/en/latest/AdministratorGuide/Resources/Storage/#available-protocol-plugins

**Comment by kosack** [comment]
so perhaps we should just stick with the standard copy access for now until we find there is a bottleneck?

**Comment by arrabito** [comment]
What is deprecated in DIRAC is the usage of the xrootd python bindings, which has been replaced by the usage of GFAL2_XROOT plugin.
Then, in my opinion it's not something urgent to put in place, but we should keep it in mind and implement it when needed (or even before if we have time). 
Just let me know when you want to set it up and I will do the necessary changes.

**Comment by jlenain** [comment]
Hi @kosack , @arrabito ,

Sorry to come back so late on this.
So if I understood correctly, the current workflow for the interactions of `ctapipe` with CTA-DIRAC is the following:

1. Locally copy files needed as input for ctapipe using DIRAC
2. `conda activate ctapipe`
3. run `ctapipe` on the local files

Is that correct ?

**Comment by jlenain** [comment]
Hi @kosack , @arrabito ,

Sorry to come back so late on this.
So if I understood correctly, the current workflow for the interactions of ctapipe with CTA-DIRAC is the following:

    Locally copy files needed as input for ctapipe using DIRAC
    conda activate ctapipe
    run ctapipe on the local files

Is that correct ?

**Comment by arrabito** [comment]
Yes, this is correct.

**Comment by kosack** [comment]
I think in a properly written Dirac job, the user doesn't explicitly do the copy, DIRAC handles it automatically (the user just has to list the input files in the job definition).  @arrabito is that correct?

**Comment by arrabito** [comment]
Exactly.

**Comment by jlenain** [comment]
Yes, I understood DIRAC can handle the copy of input files as soon as the job enters a working node.

OK, thanks a lot for all the information, it's clear to me now.
The workflow seems perfectly sound as is.

Closing this.
