### ISSUE TITLE
Empty array in DQM module (`camera_monitoring.py`)

### ISSUE THREAD

**Issue by sona-patel** [cta-observatory/nectarchain#44]
The `camera_monitoring.py` gives the error when there are no times in `nectarcam_monitoring_db*.sqlite` corresponding to times in fits file. 

Eg. for run 3936, it throws a ValueError [here](https://github.com/cta-observatory/nectarchain/blob/d5f0b22089ff618dc2b1754d6142116ec2b9b6a7/src/nectarchain/dqm/camera_monitoring.py#L87) in `FinishRun()`:

`TotalDrawers = np.max(self.DrawerNum2)`
 
I think, it will good to add check for the empty numpy for such cases.

**Comment by hashkar** [comment]
example for run 3075: 
first event at  time (evt.trigger.time.value): 1.64569535e+09
last event at: 1645695376.5700557
runs start time using (evt1.nectarcam.tel[0].svc.date): 1645695260
the times in the sqlie file on the 24th are [1645704002.271766 1645704002.271766 1645704062.612017 ...
 1645790364.432299 1645790364.432299 1645790364.432299]
KNOWING THAT the filwe on the 23rd should be used but runs start ime gives the 24th. Maybe this hsould be fixed instead of fixing the code? +
